### ISSUE TITLE
Can't open MIST in FIJI after the recent update.

### ISSUE THREAD

**Issue by stfxavier** [usnistgov/MIST#29]
Hi, 

I can't open MIST after the recent update with the messages below,

(Fiji Is Just) ImageJ 2.3.0/1.53q; Java 1.8.0_172 [64-bit]; Windows 10 10.0; 252MB of 48881MB (<1%)

java.lang.IllegalArgumentException: No enum constant gov.nist.isg.mist.lib.executor.StitchingExecutor.StitchingType.CUDA
            at java.lang.Enum.valueOf(Enum.java:238)
            at gov.nist.isg.mist.lib.executor.StitchingExecutor$StitchingType.valueOf(StitchingExecutor.java:94)
            at gov.nist.isg.mist.gui.params.utils.PreferencesUtils.loadPrefProgramType(PreferencesUtils.java:121)
            at gov.nist.isg.mist.gui.params.AdvancedParameters.loadParams(AdvancedParameters.java:342)
            at gov.nist.isg.mist.gui.params.StitchingAppParams.loadParams(StitchingAppParams.java:115)
            at gov.nist.isg.mist.StitchingGUIFrame.loadPreviousRunParams(StitchingGUIFrame.java:289)
            at gov.nist.isg.mist.StitchingGUIFrame.display(StitchingGUIFrame.java:275)
            at gov.nist.isg.mist.MISTMain.runApp(MISTMain.java:137)
            at gov.nist.isg.mist.MISTMain.run(MISTMain.java:267)
            at ij.IJ.runUserPlugIn(IJ.java:243)
            at ij.IJ.runPlugIn(IJ.java:204)
            at ij.Executer.runCommand(Executer.java:152)
            at ij.Executer.run(Executer.java:70)
            at java.lang.Thread.run(Thread.java:748)

**Comment by tblattner** [comment]
Hello!

Thanks for the bug report. I've done a hotfix for this issue and pushed it into MIST. You should be able to update in Fiji to get this new version to resolve this issue.
